---
apiVersion: v1
kind: Namespace
metadata:
  name: ansibledemo1
  labels:
    app: ansible
---
apiVersion: v1
stringData:
  token: "<ansible tower access token>"
  host: "https://ansible-tower-web-svc-tower-fake.apps.hivemind-b.aws.red-chesterfield.com/"
kind: Secret
metadata:
  annotations:
  name: toweraccess
  namespace: ansibledemo1
type: Opaque
