apiVersion: v1                    
kind: Namespace
metadata:
  name: ansible-scale-multi-jobs-1000
---
apiVersion: v1                    
kind: Namespace
metadata:
  name: ansible-scale
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ansible-scale-multi-jobs-1000
  namespace: ansible-scale-multi-jobs-1000
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - ansible-scale-multi-jobs-1000
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ansible-scale
  namespace: ansible-scale
spec:
  type: git
  pathname: 'https://github.com/ruici-h/application-lifecycle-samples'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ansible-scale-multi-jobs-1000
  namespace: ansible-scale-multi-jobs-1000
  labels:
    app: ansible-scale-multi-jobs-1000
  annotations:
    apps.open-cluster-management.io/github-path: ansible-large-scale/ansible-multi-jobs
    apps.open-cluster-management.io/github-branch: main
spec:
  hooksecretref:
    namespace: default
    name: ansible-fake
  channel: ansible-scale/ansible-scale
  placement:
    placementRef:
      kind: Placement
      name: ansible-scale-multi-jobs-1000-placement-1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: ansible-scale-multi-jobs-1000-placement-1
  namespace: ansible-scale-multi-jobs-1000
  labels:
    app: ansible-scale-multi-jobs-1000
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          vendor: OpenShift
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: ansible-scale-multi-jobs-1000
  name: global
spec:
  clusterSet: global